# Generated by Django 3.2.7 on 2021-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='media/Team/%Y/%m/%d/'),
        ),
    ]
