# Generated by Django 3.2.7 on 2021-09-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_alter_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
