# Generated by Django 3.2.7 on 2021-09-13 09:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210913_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
