# Generated by Django 3.2.7 on 2021-09-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_youtuber_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='is_features',
            new_name='is_featured',
        ),
    ]
